graph LR
  module_src_features_models_constants_architectureModels_ts["src/features/models/constants/architectureModels.ts"]
  module_src_features_models_domain_listArchitectureModels_test_ts["src/features/models/domain/listArchitectureModels.test.ts"]
  module_src_features_models_domain_listArchitectureModels_ts["src/features/models/domain/listArchitectureModels.ts"]
  module_src_index_ts["src/index.ts"]
  module_src_types_architectureModel_ts["src/types/architectureModel.ts"]
  module_src_features_models_constants_architectureModels_ts --> module_src_types_architectureModel_ts
  module_src_features_models_domain_listArchitectureModels_test_ts --> module_src_features_models_domain_listArchitectureModels_ts
  module_src_features_models_domain_listArchitectureModels_ts --> module_src_features_models_constants_architectureModels_ts
  module_src_features_models_domain_listArchitectureModels_ts --> module_src_types_architectureModel_ts
